version: 2.1
orbs:
  pcs: prisma_cloud/devops_security@3.0.4
  pc_iac: bridgecrew/bridgecrew@1.0.3
jobs:
  scan_image:
    executor: pcs/compute
    steps:
      - checkout
      - run: 'docker pull nginx'
      - pcs/scan_image:
          prisma_cloud_compute_url: $prisma_cloud_compute_url
          prisma_cloud_compute_username: $prisma_cloud_access_key
          prisma_cloud_compute_password: prisma_cloud_secret_key
          prisma_cloud_scan_image: nginx
          reports: csv,junit
  build:
    executor: pac_iac/default 
    environment:
      PRISMA_API_URL: $prisma_cloud_compute_url
    steps:
      - checkout
      - pc_iac/scan:
          directory: .
          api-key-variable: $prisma_cloud_access_key::$prisma_cloud_secret_key
workflows:
  scan:
    jobs:
      - scan_image
